name: tetris_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.10.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  flame_audio: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Sekcja Fluttera
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/audio/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

# <-- POPRAWKA: Sekcja 'flutter_launcher_icons' jest teraz na zewnątrz
#     sekcji 'flutter:', na głównym poziomie wcięć.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/moja_ikonka.png"
  min_sdk_android: 21